package p233q2;

/* renamed from: q2.p */
/* loaded from: classes.dex */
public enum EnumC4146p {
    ALWAYS_PRINT_LOGS,
    PRINT_LOGS_WHEN_NO_CALLBACKS_DEFINED,
    PRINT_LOGS_WHEN_GLOBAL_CALLBACK_NOT_DEFINED,
    PRINT_LOGS_WHEN_SESSION_CALLBACK_NOT_DEFINED,
    NEVER_PRINT_LOGS
}
